const buildRegularPolygon = require('../shape/buildRegularPolygon');
const polygonsToSvg = require('./polygonsToSvg');
const test = require('ava');

test('Triangle', t => {
  const svg = polygonsToSvg({}, [buildRegularPolygon({ edges: 3 })]);
  t.is(svg,
       ['<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by jsxcad -->',
        '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1 Tiny//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11-tiny.dtd">',
        '<svg baseProfile="tiny" height="0.86603 mm" width="1 mm" viewBox="0 0 1 0.86603" version="1.1" xmlns="http://www.w3.org/2000/svg">',
        '<path d="M1.5 0.86603 L0 1.73206 L0 0"/>',
        '</svg>']
           .join('\n'));
});

test('Octagon', t => {
  const svg = polygonsToSvg({}, [buildRegularPolygon({ edges: 8 })]);
  t.is(svg,
       ['<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by jsxcad -->',
        '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1 Tiny//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11-tiny.dtd">',
        '<svg baseProfile="tiny" height="1 mm" width="1 mm" viewBox="0 0 1 1" version="1.1" xmlns="http://www.w3.org/2000/svg">',
        '<path d="M2 1 L1.70711 1.70711 L1 2 L0.29289 1.70711 L0 1 L0.29289 0.29289 L1 0 L1.70711 0.29289"/>',
        '</svg>']
           .join('\n'));
});
