const { publish } = require('@jsxcad/provide');

module.exports =
    publish({ base: '@jsxcad/math-vec3', require },
            'abs',
            'add',
            'angle',
            'canonicalize',
            'create',
            'cross',
            'distance',
            'divide',
            'dot',
            'equals',
            'fromPoint',
            'fromScalar',
            'fromValues',
            'fromVec2',
            'length',
            'lerp',
            'max',
            'min',
            'multiply',
            'negate',
            'normalize',
            'random',
            'rotateX',
            'rotateY',
            'rotateZ',
            'scale',
            'squaredDistance',
            'squaredLength',
            'subtract',
            'toString',
            'transform',
            'unit');
