#!/bin/bash

cp algorithm/cgal/dist/main.js es6/jsxcad-algorithm-cgal.js
cp algorithm/color/dist/main.js es6/jsxcad-algorithm-color.js
cp algorithm/contour/dist/main.js es6/jsxcad-algorithm-contour.js
cp algorithm/material/dist/main.js es6/jsxcad-algorithm-material.js
cp algorithm/pack/dist/main.js es6/jsxcad-algorithm-pack.js
cp algorithm/quantize/dist/main.js es6/jsxcad-algorithm-quantize.js
cp algorithm/shape/dist/main.js es6/jsxcad-algorithm-shape.js
cp algorithm/text/dist/main.js es6/jsxcad-algorithm-text.js
cp algorithm/toolpath/dist/main.js es6/jsxcad-algorithm-toolpath.js
cp algorithm/verlet/dist/main.js es6/jsxcad-algorithm-verlet.js
cp algorithm/watertight/dist/main.js es6/jsxcad-algorithm-watertight.js
cp api/observablehq/dist/main.js es6/jsxcad-api-observablehq.js
cp api/v1/dist/main.js es6/jsxcad-api-v1.js
cp api/v1-armature/dist/main.js es6/jsxcad-api-v1-armature.js
cp api/v1-connector/dist/main.js es6/jsxcad-api-v1-connector.js
cp api/v1-cursor/dist/main.js es6/jsxcad-api-v1-cursor.js
cp api/v1-deform/dist/main.js es6/jsxcad-api-v1-deform.js
cp api/v1-dst/dist/main.js es6/jsxcad-api-v1-dst.js
cp api/v1-dxf/dist/main.js es6/jsxcad-api-v1-dxf.js
cp api/v1-extrude/dist/main.js es6/jsxcad-api-v1-extrude.js
cp api/v1-font/dist/main.js es6/jsxcad-api-v1-font.js
cp api/v1-gcode/dist/main.js es6/jsxcad-api-v1-gcode.js
cp api/v1-item/dist/main.js es6/jsxcad-api-v1-item.js
cp api/v1-layout/dist/main.js es6/jsxcad-api-v1-layout.js
cp api/v1-line2/dist/main.js es6/jsxcad-api-v1-line2.js
cp api/v1-math/dist/main.js es6/jsxcad-api-v1-math.js
cp api/v1-pdf/dist/main.js es6/jsxcad-api-v1-pdf.js
cp api/v1-plan/dist/main.js es6/jsxcad-api-v1-plan.js
cp api/v1-plans/dist/main.js es6/jsxcad-api-v1-plans.js
cp api/v1-png/dist/main.js es6/jsxcad-api-v1-png.js
cp api/v1-shape/dist/main.js es6/jsxcad-api-v1-shape.js
cp api/v1-shapefile/dist/main.js es6/jsxcad-api-v1-shapefile.js
cp api/v1-shapes/dist/main.js es6/jsxcad-api-v1-shapes.js
cp api/v1-shell/dist/main.js es6/jsxcad-api-v1-shell.js
cp api/v1-stl/dist/main.js es6/jsxcad-api-v1-stl.js
cp api/v1-svg/dist/main.js es6/jsxcad-api-v1-svg.js
cp api/v1-threejs/dist/main.js es6/jsxcad-api-v1-threejs.js
cp api/v1-tools/dist/main.js es6/jsxcad-api-v1-tools.js
cp api/v1-units/dist/main.js es6/jsxcad-api-v1-units.js
cp cache/dist/main.js es6/jsxcad-cache.js
cp compiler/dist/main.js es6/jsxcad-compiler.js
cp convert/dst/dist/main.js es6/jsxcad-convert-dst.js
cp convert/dxf/dist/main.js es6/jsxcad-convert-dxf.js
cp convert/gcode/dist/main.js es6/jsxcad-convert-gcode.js
cp convert/ldraw/dist/main.js es6/jsxcad-convert-ldraw.js
cp convert/notebook/dist/main.js es6/jsxcad-convert-notebook.js
cp convert/pdf/dist/main.js es6/jsxcad-convert-pdf.js
cp convert/png/dist/main.js es6/jsxcad-convert-png.js
cp convert/shapefile/dist/main.js es6/jsxcad-convert-shapefile.js
cp convert/stl/dist/main.js es6/jsxcad-convert-stl.js
cp convert/svg/dist/main.js es6/jsxcad-convert-svg.js
cp convert/threejs/dist/main.js es6/jsxcad-convert-threejs.js
cp data/shape/dist/main.js es6/jsxcad-data-shape.js
cp geometry/bsp/dist/main.js es6/jsxcad-geometry-bsp.js
cp geometry/graph/dist/main.js es6/jsxcad-geometry-graph.js
cp geometry/halfedge/dist/main.js es6/jsxcad-geometry-halfedge.js
cp geometry/path/dist/main.js es6/jsxcad-geometry-path.js
cp geometry/paths/dist/main.js es6/jsxcad-geometry-paths.js
cp geometry/plan/dist/main.js es6/jsxcad-geometry-plan.js
cp geometry/points/dist/main.js es6/jsxcad-geometry-points.js
cp geometry/polygons/dist/main.js es6/jsxcad-geometry-polygons.js
cp geometry/solid-boolean/dist/main.js es6/jsxcad-geometry-solid-boolean.js
cp geometry/solid/dist/main.js es6/jsxcad-geometry-solid.js
cp geometry/surface/dist/main.js es6/jsxcad-geometry-surface.js
cp geometry/tagged/dist/main.js es6/jsxcad-geometry-tagged.js
cp math/line2/dist/main.js es6/jsxcad-math-line2.js
cp math/line3/dist/main.js es6/jsxcad-math-line3.js
cp math/mat4/dist/main.js es6/jsxcad-math-mat4.js
cp math/plane/dist/main.js es6/jsxcad-math-plane.js
cp math/poly3/dist/main.js es6/jsxcad-math-poly3.js
cp math/utils/dist/main.js es6/jsxcad-math-utils.js
cp math/vec2/dist/main.js es6/jsxcad-math-vec2.js
cp math/vec3/dist/main.js es6/jsxcad-math-vec3.js
cp math/vec4/dist/main.js es6/jsxcad-math-vec4.js
cp sys/dist/main.js es6/jsxcad-sys.js
cp ui/notebook/dist/main.js es6/jsxcad-ui-notebook.js
cp ui/threejs/dist/main.js es6/jsxcad-ui-threejs.js
cp ui/v1/dist/main.js es6/jsxcad-ui-v1.js
cp ui/v1/dist/webworker.js es6/jsxcad-ui-v1-webworker.js

git add es6/*.js
