const { publish } = require('@jsxcad/provide');

module.exports =
    publish({ base: '@jsxcad/math-vec2', require },
            'abs',
            'add',
            'angle',
            'angleDegrees',
            'angleRadians',
            'canonicalize',
            'cross',
            'distance',
            'divide',
            'dot',
            'equals',
            'fromAngle',
            'fromAngleDegrees',
            'fromAngleRadians',
            'fromPoint',
            'fromScalar',
            'fromValues',
            'length',
            'lerp',
            'max',
            'min',
            'multiply',
            'negate',
            'normal',
            'normalize',
            'rotate',
            'scale',
            'squaredDistance',
            'squaredLength',
            'subtract',
            'transform');
