. emsdk/emsdk_env.sh

clang-format --style=google -i *.h *.cc

# emcc -Wunused -Wunused-function -O3 -sSTACK_SIZE=10485760 -fwasm-exceptions -fexceptions -o cgal_browser.js -DGLM_ENABLE_EXPERIMENTAL -DJOT_MANIFOLD_ENABLED -DCGAL_USE_GLPK -DCGAL_ALWAYS_ROUND_TO_NEAREST -DCGAL_WITH_GMPXX -DCGAL_USE_GMPXX=1 -DCGAL_DO_NOT_USE_BOOST_MP -DBOOST_ALL_NO_LIB emscripten.cc -I . -I ./glm -I ./glm/glm -I ./wasm/include -I ./manifold/include/ -I ./manifold/include/manifold/ -I emsdk/upstream/emscripten/system/include/polyclipping -I emsdk/upstream/emscripten/system/include -static -flto -DIGNORE_NO_ATOMICS=1 -DOCCT_NO_PLUGINS -frtti -std=c++1z --bind ./wasm/lib/libglpk.a ./wasm/lib/libgmpxx.a ./wasm/lib/libmpfr.a ./wasm/lib/libgmp.a ./wasm/lib/libmanifold.a ./wasm/lib/libClipper2.a -s MODULARIZE=1 -s USE_ES6_IMPORT_META=0 -s USE_BOOST_HEADERS=1 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB -s ASSERTIONS=0 -ferror-limit=10000 && mv cgal_browser.js cgal_browser.cjs

# emcc -Wunused -Wunused-function -O3 -sSTACK_SIZE=10485760 -fwasm-exceptions -fexceptions -o cgal_browser.js -DGLM_ENABLE_EXPERIMENTAL -DJOT_MANIFOLD_ENABLED -DCGAL_USE_GLPK -DCGAL_ALWAYS_ROUND_TO_NEAREST -DCGAL_WITH_GMPXX -DCGAL_USE_GMPXX=1 -DCGAL_DO_NOT_USE_BOOST_MP -DBOOST_ALL_NO_LIB emscripten.cc -I . -I ./glm -I ./glm/glm -I ./wasm/include -I ./manifold/include/ -I ./manifold/include/manifold/ -I emsdk/upstream/emscripten/system/include/polyclipping -I emsdk/upstream/emscripten/system/include -static -flto -DIGNORE_NO_ATOMICS=1 -DOCCT_NO_PLUGINS -frtti -std=c++1z --bind ./wasm/lib/libglpk.a ./wasm/lib/libgmpxx.a ./wasm/lib/libmpfr.a ./wasm/lib/libgmp.a ./wasm/lib/libmanifold.a -s MODULARIZE=1 -s USE_ES6_IMPORT_META=0 -s USE_BOOST_HEADERS=1 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB -s ASSERTIONS=0 -ferror-limit=10000 && mv cgal_browser.js cgal_browser.cjs

# -s DEMANGLE_SUPPORT=1

# emcc -Wunused -Wunused-function -O3 -sSTACK_SIZE=10485760 -fwasm-exceptions -fexceptions -o cgal_browser.js -DGLM_ENABLE_EXPERIMENTAL -DCGAL_USE_GLPK -DCGAL_ALWAYS_ROUND_TO_NEAREST -DCGAL_WITH_GMPXX -DCGAL_USE_GMPXX=1 -DCGAL_DO_NOT_USE_BOOST_MP -DBOOST_ALL_NO_LIB emscripten.cc -I . -I ./glm -I ./glm/glm -I ./wasm/include -I ./manifold/include/ -I ./manifold/include/manifold/ -I emsdk/upstream/emscripten/system/include/polyclipping -I emsdk/upstream/emscripten/system/include -static -flto -DIGNORE_NO_ATOMICS=1 -DOCCT_NO_PLUGINS -frtti -std=c++1z --bind ./wasm/lib/libglpk.a ./wasm/lib/libgmpxx.a ./wasm/lib/libmpfr.a ./wasm/lib/libgmp.a ./wasm/lib/libmanifold.a -s MODULARIZE=1 -s USE_ES6_IMPORT_META=0 -s USE_BOOST_HEADERS=1 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB -s ASSERTIONS=0 -ferror-limit=10000 && mv cgal_browser.js cgal_browser.cjs

emcc --profiling-funcs -Wunused -Wunused-function -O3 -sSTACK_SIZE=10485760 -fwasm-exceptions -fexceptions -o cgal_browser.js -DGLM_ENABLE_EXPERIMENTAL -DCGAL_USE_GLPK -DCGAL_ALWAYS_ROUND_TO_NEAREST -DCGAL_WITH_GMPXX -DCGAL_USE_GMPXX=1 -DCGAL_DO_NOT_USE_BOOST_MP -DBOOST_ALL_NO_LIB emscripten.cc -I . -I ./glm -I ./glm/glm -I ./wasm/include -I ./manifold/include/ -I ./manifold/include/manifold/ -I emsdk/upstream/emscripten/system/include/polyclipping -I emsdk/upstream/emscripten/system/include -static -flto -DIGNORE_NO_ATOMICS=1 -DOCCT_NO_PLUGINS -frtti -std=c++1z --bind ./wasm/lib/libglpk.a ./wasm/lib/libgmpxx.a ./wasm/lib/libmpfr.a ./wasm/lib/libgmp.a ./wasm/lib/libmanifold.a -s MODULARIZE=1 -s USE_ES6_IMPORT_META=0 -s USE_BOOST_HEADERS=1 -s ALLOW_MEMORY_GROWTH=1 -s MAXIMUM_MEMORY=4GB -s ASSERTIONS=0 -ferror-limit=10000 && mv cgal_browser.js cgal_browser.cjs
