import {
  getLayouts,
  getLeafs,
  isNotVoid,
  measureBoundingBox,
  taggedLayers,
  taggedLayout,
  visit,
} from '@jsxcad/geometry-tagged';

import Box from './Box.js';
import Empty from './Empty.js';
import Group from './Group.js';
import Hershey from './Hershey.js';
import Shape from '@jsxcad/api-v1-shape';

const MIN = 0;
const MAX = 1;
const X = 0;
const Y = 1;

const getItemNames = (geometry) => {
  const names = new Set();
  const op = (geometry, descend) => {
    if (
      geometry.type === 'item' &&
      isNotVoid(geometry) &&
      geometry.tags &&
      geometry.tags.some((tag) => tag.startsWith('item/'))
    ) {
      geometry.tags
        .filter((tag) => tag.startsWith('item/'))
        .forEach((tag) => names.add(tag.substring(5)));
    } else {
      descend();
    }
  };
  visit(geometry, op);
  return [...names].sort();
};

const buildLayoutGeometry = ({
  layer,
  packSize,
  pageWidth,
  pageLength,
  margin,
}) => {
  const itemNames = getItemNames(layer).filter((name) => name !== '');
  const labelScale = 0.0125 * 10;
  const size = [pageWidth, pageLength];
  const r = (v) => Math.floor(v * 100) / 100;
  // const title = `${r(pageWidth)} x ${r(pageLength)} : ${itemNames.join(', ')}`;
  const fontHeight = Math.max(pageWidth, pageLength) * labelScale;
  const font = Hershey(fontHeight);
  const title = [];
  title.push(font(`${r(pageWidth)} x ${r(pageLength)}`));
  for (let nth = 0; nth < itemNames.length; nth++) {
    title.push(font(itemNames[nth]).y((nth + 1) * fontHeight));
  }
  const visualization = Box(
    Math.max(pageWidth, margin),
    Math.max(pageLength, margin)
  )
    .outline()
    .and(
      Group(...title).move(pageWidth / -2, (pageLength * (1 + labelScale)) / 2)
    )
    .color('red')
    .sketch()
    .toGeometry();
  return taggedLayout(
    { size, margin, title, marks: packSize },
    layer,
    visualization
  );
};

export const Page = (
  {
    size,
    pageMargin = 5,
    itemMargin = 1,
    itemsPerPage = Infinity,
    pack = true,
  },
  ...shapes
) => {
  const margin = itemMargin;
  const layers = [];
  for (const shape of shapes) {
    for (const leaf of getLeafs(shape.toDisjointGeometry())) {
      layers.push(leaf);
    }
  }
  if (!pack) {
    const layer = taggedLayers({}, ...layers);
    const packSize = measureBoundingBox(layer);
    const pageWidth =
      // Math.max(1, packSize[MAX][X] - packSize[MIN][X]) + pageMargin * 2;
      Math.max(
        1,
        Math.abs(packSize[MAX][X] * 2),
        Math.abs(packSize[MIN][X] * 2)
      ) +
      pageMargin * 2;
    const pageLength =
      // Math.max(1, packSize[MAX][Y] - packSize[MIN][Y]) + pageMargin * 2;
      Math.max(
        1,
        Math.abs(packSize[MAX][Y] * 2),
        Math.abs(packSize[MIN][Y] * 2)
      ) +
      pageMargin * 2;
    return Shape.fromGeometry(
      buildLayoutGeometry({ layer, packSize, pageWidth, pageLength, margin })
    );
  } else if (size) {
    // Content fits to page size.
    const packSize = [];
    const content = Shape.fromGeometry(taggedLayers({}, ...layers)).pack({
      size,
      pageMargin,
      itemMargin,
      perLayout: itemsPerPage,
      packSize,
    });
    if (packSize.length === 0) {
      throw Error('Packing failed');
    }
    const pageWidth = Math.max(1, packSize[MAX][X] - packSize[MIN][X]);
    const pageLength = Math.max(1, packSize[MAX][Y] - packSize[MIN][Y]);
    const plans = [];
    for (const layer of content.toDisjointGeometry().content[0].content) {
      plans.push(
        buildLayoutGeometry({ layer, packSize, pageWidth, pageLength, margin })
      );
    }
    return Shape.fromGeometry(taggedLayers({}, ...plans));
  } else {
    const packSize = [];
    // Page fits to content size.
    const content = Shape.fromGeometry(taggedLayers({}, ...layers)).pack({
      pageMargin,
      itemMargin,
      perLayout: itemsPerPage,
      packSize,
    });
    if (packSize.length === 0) {
      throw Error('Packing failed');
    }
    // FIX: Using content.size() loses the margin, which is a problem for repacking.
    // Probably page plans should be generated by pack and count toward the size.
    const pageWidth = packSize[MAX][X] - packSize[MIN][X];
    const pageLength = packSize[MAX][Y] - packSize[MIN][Y];
    if (isFinite(pageWidth) && isFinite(pageLength)) {
      const plans = [];
      for (const layer of content.toDisjointGeometry().content[0].content) {
        const layoutGeometry = buildLayoutGeometry({
          layer,
          packSize,
          pageWidth,
          pageLength,
          margin,
        });
        Shape.fromGeometry(layoutGeometry);
        plans.push(layoutGeometry);
      }
      return Shape.fromGeometry(taggedLayers({}, ...plans));
    } else {
      return Empty();
    }
  }
};

const PageMethod = function (options = {}) {
  return Page(options, this);
};
Shape.prototype.page = PageMethod;

export default Page;

export const ensurePages = (geometry, depth = 0) => {
  const pages = getLayouts(geometry);
  if (pages.length === 0 && depth === 0) {
    return ensurePages(
      Page({ pack: false }, Shape.fromGeometry(geometry)).toDisjointGeometry(),
      depth + 1
    );
  } else {
    return pages;
  }
};

const FixMethod = function (options = {}) {
  return Page({ ...options, pack: false }, this);
};
Shape.prototype.fix = FixMethod;
