import { buildRegularPolygon } from '@jsxcad/algorithm-shape';
import test from 'ava';
import { toSvg } from './toSvg';

test('Triangle', async t => {
  const svg = await toSvg({ padding: 2 },
                          { disjointAssembly: [{ z0Surface: [buildRegularPolygon({ edges: 3 })], tags: ['color/blue'] },
                                               { paths: [buildRegularPolygon({ edges: 3 })], tags: ['color/red'] }] });
  t.is(svg,
       `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by jsxcad -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1 Tiny//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11-tiny.dtd">
<svg baseProfile="tiny" height="1.7320508075688772mm" width="1.5000000000000004mm" viewBox="-2 -2 5.5 5.732050807568877" version="1.1" stroke="black" stroke-width=".1" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill="blue" d="M1.7500000000000002 0.8660254037844386 L0.25000000000000044 1.7320508075688772 L0.24999999999999978 1.1102230246251565e-16 z"/>
<path stroke="red" d="M1.7500000000000002 0.8660254037844386 L0.25000000000000044 1.7320508075688772 L0.24999999999999978 1.1102230246251565e-16 z"/>
</svg>`);
});

test('Octagon', async t => {
  const svg = await toSvg({}, { surface: [buildRegularPolygon({ edges: 8 })] });
  t.is(svg,
       `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by jsxcad -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1 Tiny//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11-tiny.dtd">
<svg baseProfile="tiny" height="2mm" width="2mm" viewBox="0 0 2 2" version="1.1" stroke="black" stroke-width=".1" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill="black" d="M1.7071067811865475 1.7071067811865475 L1.7071067811865475 0.2928932188134523 L2 1 z"/>
<path fill="black" d="M1 2 L1.7071067811865475 0.2928932188134523 L1.7071067811865475 1.7071067811865475 z"/>
<path fill="black" d="M1 2 L0.9999999999999998 0 L1.7071067811865475 0.2928932188134523 z"/>
<path fill="black" d="M0.29289321881345254 1.7071067811865475 L0.9999999999999998 0 L1 2 z"/>
<path fill="black" d="M0.29289321881345254 1.7071067811865475 L0.2928932188134523 0.29289321881345254 L0.9999999999999998 0 z"/>
<path fill="black" d="M0.2928932188134523 0.29289321881345254 L0.29289321881345254 1.7071067811865475 L0 1.0000000000000002 z"/>
</svg>`);
});
