import { buildRegularPolygon } from '@jsxcad/algorithm-shape';
import test from 'ava';
import { toSvg } from './toSvg';

test('Triangle', async t => {
  const svg = await toSvg({ padding: 2 },
                          { disjointAssembly: [{ z0Surface: [buildRegularPolygon({ edges: 3 })], tags: ['color/blue'] },
                                               { paths: [buildRegularPolygon({ edges: 3 })], tags: ['color/red'] }] });
  t.is(svg,
       `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by jsxcad -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1 Tiny//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11-tiny.dtd">
<svg baseProfile="tiny" height="1.7320508075688772 mm" width="1.5000000000000004 mm" viewBox="-2 -2 5.5 5.732050807568877" version="1.1" stroke="black" stroke-width=".1" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill="blue" d="M1 0 L-0.4999999999999998 0.8660254037844387 L-0.5000000000000004 -0.8660254037844385 z"/>
<path stroke="red" d="M1 0 L-0.4999999999999998 0.8660254037844387 L-0.5000000000000004 -0.8660254037844385 z"/>
</svg>`);
});

test('Octagon', async t => {
  const svg = await toSvg({}, { surface: [buildRegularPolygon({ edges: 8 })] });
  t.is(svg,
       `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by jsxcad -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1 Tiny//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11-tiny.dtd">
<svg baseProfile="tiny" height="2 mm" width="2 mm" viewBox="0 0 2 2" version="1.1" stroke="black" stroke-width=".1" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill="black" d="M0.7071067811865476 0.7071067811865475 L0.7071067811865474 -0.7071067811865477 L1 0 z"/>
<path fill="black" d="M6.123233995736766e-17 1 L0.7071067811865474 -0.7071067811865477 L0.7071067811865476 0.7071067811865475 z"/>
<path fill="black" d="M6.123233995736766e-17 1 L-1.8369701987210297e-16 -1 L0.7071067811865474 -0.7071067811865477 z"/>
<path fill="black" d="M-0.7071067811865475 0.7071067811865476 L-1.8369701987210297e-16 -1 L6.123233995736766e-17 1 z"/>
<path fill="black" d="M-0.7071067811865475 0.7071067811865476 L-0.7071067811865477 -0.7071067811865475 L-1.8369701987210297e-16 -1 z"/>
<path fill="black" d="M-0.7071067811865477 -0.7071067811865475 L-0.7071067811865475 0.7071067811865476 L-1 1.2246467991473532e-16 z"/>
</svg>`);
});
