import './add.js';
import './addTo.js';
import './align.js';
import './as.js';
import './assemble.js';
import './bench.js';
import './canonicalize.js';
import './clip.js';
import './clipFrom.js';
import './color.js';
import './colors.js';
import './constantLaser.js';
import './cut.js';
import './cutFrom.js';
import './each.js';
import './faces.js';
import './feedRate.js';
import './fuse.js';
import './hole.js';
import './inSolids.js';
import './intersection.js';
import './keep.js';
import './graph.js';
import './group.js';
import './laserPower.js';
import './material.js';
import './move.js';
import './moveX.js';
import './moveY.js';
import './moveZ.js';
import './noHoles.js';
import './op.js';
import './openEdges.js';
import './orient.js';
import './pause.js';
import './paths.js';
import './peg.js';
import './plan.js';
import './readShape.js';
import './rotate.js';
import './rotateX.js';
import './rotateY.js';
import './rotateZ.js';
import './scale.js';
import './size.js';
import './sketch.js';
import './solids.js';
import './spindleRpm.js';
import './surfaces.js';
import './tags.js';
import './test.js';
import './tool.js';
import './toolpaths.js';
import './trace.js';
import './translate.js';
import './turn.js';
import './turnX.js';
import './turnY.js';
import './turnZ.js';
import './union.js';
import './weld.js';
import './wireframe.js';
import './wireframeFaces.js';
import './with.js';
import './writeShape.js';

import { loadGeometry, saveGeometry } from './saveGeometry.js';

import Shape from './Shape.js';
import log from './log.js';

export { Shape, loadGeometry, log, saveGeometry };
export { getPegCoords, orient, shapeMethod } from './peg.js';

export { weld } from './weld.js';

export default Shape;
