const { publish } = require('@jsxcad/provide');

module.exports =
    publish({ base: '@jsxcad/math-mat4', require },
            'add',
            'clone',
            'constants',
            'create',
            'equals',
            'fromRotation',
            'fromScaling',
            'fromTranslation',
            'fromValues',
            'fromXRotation',
            'fromYRotation',
            'fromZRotation',
            'identity',
            'isMirroring',
            'mirror',
            'mirrorByPlane',
            'multiply',
            'rightMultiplyVec2',
            'rightMultiplyVec3',
            'rotate',
            'rotateX',
            'rotateY',
            'rotateZ',
            'scale',
            'subtract',
            'toString',
            'translate');
